name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff

      - name: Static checks (non-blocking)
        run: |
          ruff --version
          ruff check app || true

      - name: Sanity import
        run: |
          python -m compileall app
          python - <<'PY'
          from app.main import app
          print('App loaded:', bool(app))
          PY


